name: "mediapipe_onnx"
platform: "onnxruntime_onnx"
max_batch_size : 0
input [
  {
    name: "input_1"
    data_type: TYPE_FP32
    dims: [1,224,224,3]
  }
]
output [
  {
    name: "Identity"
    data_type: TYPE_FP32
    dims: [1,63]
  },
  {
    name: "Identity_1"
    data_type: TYPE_FP32
    dims: [1,1]
  },
  {
    name: "Identity_2"
    data_type: TYPE_FP32
    dims: [1,1]
  }
]