name: "keypoint_onnx"
platform: "onnxruntime_onnx"
max_batch_size : 0
input [
  {
    name: "input_1"
    data_type: TYPE_FP32
    dims: [-1, 42]
  }
]
output [
  {
    name: "Identity"
    data_type: TYPE_FP32
    dims: [-1, 4]
  }
]